### ISSUE TITLE
请问可以直接下载代码，然后yarn install，那npm run serve 运行吗

### ISSUE THREAD

**Issue by enkialtria** [h7ml/vue-amis-sdk#92]

**Comment by enkialtria** [comment]
index.js:726 Uncaught TypeError: amisCore.bindRendererEvent is not a function
    at eval (InputText.js?c991:529:1)
    at eval (InputText.js?c991:553:1)
    at ./node_modules/amis/lib/renderers/Form/InputText.js (chunk-vendors.js:5849:1)
    at __webpack_require__ (index.js:723:33)
    at fn (index.js:1040:21)
    at eval (index.js?c0d2:40:1)
    at ./node_modules/amis/lib/index.js (chunk-vendors.js:5013:1)
    at __webpack_require__ (index.js:723:33)
    at fn (index.js:1040:21)
    at 1502 (index.min.js?23e0:1:1)

**Comment by h7ml** [comment]
暂时版本回退下 使用命令 ``git reset --hard dbea0b932ce077358f4daf61ebc0a28cbb0eb620``

**Comment by h7ml** [comment]
``yarn add vue-amis-sdk@2.7.2 ``

[https://github.com/h7ml/vue-amis-sdk-examples/blob/main/package.json#L11-L15](https://github.com/h7ml/vue-amis-sdk-examples/blob/main/package.json#L11-L15)

**Comment by h7ml** [comment]
> 我出现错误 amisCore.bindRendererEvent is not a function

https://github.com/kevin361419446/amis-vue-template/issues/1 这个问题隔壁有解决方案。试试吧
